- hosts: localhost
  vars:
    xdg_data_home: "{{ lookup('env', 'XDG_DATA_HOME') }}"
    xdg_config_home: "{{ lookup('env', 'XDG_CONFIG_HOME') }}"
    xdg_state_home: "{{ lookup('env', 'XDG_STATE_HOME') }}"
  tasks:
    - import_tasks: tasks/vscode.yaml
      tags: vscode
    - import_tasks: tasks/productivity.yaml
      tags: productivity
    - import_tasks: tasks/terminal.yaml
      tags: terminal
    - import_tasks: tasks/zsh.yaml
      tags: zsh
