- hosts: localhost
  vars:
    xdg_data_home: "{{ lookup('env', 'XDG_DATA_HOME') }}"
    xdg_config_home: "{{ lookup('env', 'XDG_CONFIG_HOME') }}"
    xdg_state_home: "{{ lookup('env', 'XDG_STATE_HOME') }}"
  tasks:
    - import_tasks: tasks/vscode.yaml
      tags: vscode
    - import_tasks: tasks/productivity.yaml
      tags: productivity
    - import_tasks: tasks/terminal.yaml
      tags: terminal
    - import_tasks: tasks/zsh.yaml
      tags: zsh
    - import_tasks: tasks/bash.yaml
      tags: bash
    - import_tasks: tasks/discord.yaml
      tags: discord
    - import_tasks: tasks/docker.yaml
      tags: docker
    # Tasks that need user interaction run in the end to avoid blocking the installation
    - import_tasks: tasks/aerospace.yaml
      tags: aerospace
    - import_tasks: tasks/flameshot.yaml
      tags: flameshot
