- block:
    - name: Install AeroSpace
      homebrew_cask:
        name: nikitabobko/tap/aerospace

    - name: Hide dock
      shell:
        osascript -e 'tell application "System Events" to set the autohide of
        the dock preferences to true'

    - name: Adjust window to get missing space after dock is hidden
      shell: aerospace resize smart +100
      register: result
      failed_when: false

    - name: Allow Application AeroSpace to be used on System Settings
      shell: |
        echo "Please press any key to continue"
        read -n 1 -s

    - name: Open AeroSpace
      shell: open /Applications/AeroSpace.app

  when: ansible_os_family == 'Darwin'
