- block:
    - name: Install Rosetta (allow run Intel based code)
      shell: softwareupdate --install-rosetta --agree-to-license

    - name: Install flameshot
      homebrew_cask:
        name: flameshot

    - name: Allow Application Flameshot to be used and record the content of the Screen on System Settings
      shell: |
        echo "Please press any key to continue"
        read -n 1 -s

    - name: Run flameshot on startup
      shell: /Applications/flameshot.app/Contents/MacOS/flameshot config --autostart true

    - name: Open flameshot
      shell: open /Applications/flameshot.app

  when: ansible_os_family == 'Darwin'

- block:
    - name: Install flameshot
      become: true
      apt:
        name: flameshot

    - name: Run flameshot on startup
      shell: flameshot config --autostart true

    - name: Add flameshort custom shortcut
      shell: |
        gsettings set org.gnome.settings-daemon.plugins.media-keys custom-keybindings "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/']"
        gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/ name 'flameshot-layout-mac'
        gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/ command 'flameshot gui'
        gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/ binding '<Shift><Control><Super>p'
            gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/ name 'flameshot-layout-windows'
        gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/ command 'flameshot gui'
        gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/ binding '<Shift><Control><Alt>p'
  when: ansible_os_family == 'Debian'
